spring:
  application:
    name: spring-rest-api
  
  profiles:
    active: local


app:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:8080
  file:
    upload-dir: /Users/danyoh/XXX-AI/sr-mobile/uploads/

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

# 기본 서버 설정
server:
  port: 8080
  compression:
    enabled: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
